name: historical-ocr
channels:
  - pytorch
  - defaults
dependencies:
  - astroid=2.4.2
  - autopep8=1.5.4
  - backcall=0.2.0
  - blas=1.0
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - colorama=0.4.3
  - cudatoolkit=10.2.89
  - decorator=4.4.2
  - freetype=2.10.3
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - isort=5.6.4
  - jedi=0.17.2
  - jpeg=9b
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - lazy-object-proxy=1.4.3
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.1.0
  - lz4-c=1.9.2
  - mccabe=0.6.1
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - ninja=1.10.1
  - numpy=1.19.1
  - numpy-base=1.19.1
  - olefile=0.46
  - openssl=1.1.1h
  - parso=0.7.0
  - pickleshare=0.7.5
  - pillow=8.0.0
  - pip=20.2.3
  - prompt-toolkit=3.0.8
  - pycodestyle=2.6.0
  - pygments=2.7.2
  - pylint=2.6.0
  - python=3.8.5
  - python-dateutil=2.8.1
  - pytorch=1.6.0
  - pyzmq=19.0.2
  - setuptools=50.3.0
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - toml=0.10.1
  - torchvision=0.7.0
  - tornado=6.0.4
  - traitlets=5.0.5
  - wcwidth=0.2.5
  - wheel=0.35.1
  - wrapt=1.11.2
  - xz=5.2.5
  - zeromq=4.3.2
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - cffi==1.14.3
    - chardet==3.0.4
    - click==7.1.2
    - cmake==3.18.2.post1
    - configparser==5.0.1
    - cycler==0.10.0
    - cython==0.29.14
    - dependency-injector==4.0.0
    - docker-pycreds==0.4.0
    - filelock==3.0.12
    - gensim==3.8.3
    - gitdb==4.0.5
    - gitpython==3.1.9
    - idna==2.10
    - jellyfish==0.8.2
    - joblib==0.17.0
    - kiwisolver==1.2.0
    - matplotlib==3.3.2
    - multicoretsne==0.1
    - nltk==3.5
    - overrides==3.1.0
    - packaging==20.4
    - pandas==1.1.3
    - pathtools==0.1.2
    - promise==2.3
    - protobuf==3.13.0
    - psutil==5.7.2
    - pycparser==2.20
    - pyparsing==2.4.7
    - pytz==2020.1
    - pyyaml==5.3.1
    - regex==2020.10.15
    - requests==2.24.0
    - sacremoses==0.0.43
    - scikit-learn==0.23.2
    - scipy==1.5.2
    - seaborn==0.11.0
    - sentencepiece==0.1.94
    - sentry-sdk==0.19.0
    - shortuuid==1.0.1
    - sklearn==0.0
    - smart-open==3.0.0
    - smmap==3.0.4
    - subprocess32==3.5.4
    - termcolor==1.1.0
    - threadpoolctl==2.1.0
    - tokenizers==0.9.2
    - tqdm==4.50.2
    - transformers==3.4.0
    - urllib3==1.25.10
    - wandb==0.10.7
    - watchdog==0.10.3
