
from enums.language import Language
from enums.metric_type import MetricType

default_values = {
    'epochs': 500,
    'eval_freq': 50,
    'batch_size': 8,
    'max_training_minutes': 24 * 60,
    'device' : 'cpu',
    'seed': 42,
    'evaluate': False,
    'patience': 30,
    'consider_equal_results_as_worse': False,
    'language': Language.English,
    'shuffle': True,
    'learning_rate': 1e-5,
    'weight_decay': 1e-8,
    'momentum': 0,
    'checkpoint_name': None,
    'resume_training': False,
    'resume_checkpoint_name': None,
    'skip_best_metrics_on_resume': False,
    'data_folder': 'data',
    'experiments_folder': 'experiments',
    'cache_folder': '.cache',
    'output_folder': 'results',
    'checkpoint_folder': None,
    'metric_types': MetricType.JaccardSimilarity,
    'joint_model': False,
    'joint_model_amount': 2,
    'enable_external_logging': False,
    'train_dataset_limit_size': None,
    'validation_dataset_limit_size': None,
    'skip_validation': True,
    'run_experiments': False,
    'experiment_types': None,
    'reset_training_on_early_stop': False,
    'resets_limit': 1,
    'training_reset_epoch_limit': 1,
    'save_checkpoint_on_crash': False,
    'save_checkpoint_on_finish': False,
    'log_folder': '.logs',
    'enable_verbose_logging': False,

    'pretrained_weights': 'bert-base-cased',
    'include_pretrained_model': False,
    'pretrained_model_size': 768,
    'pretrained_max_length': None,
    'learn_new_embeddings': False,

    'fasttext_model': None,
    'include_fasttext_model': False,
    'fasttext_model_size': 300,
    'pretrained_model': None,
    'fine_tune_pretrained': False,
    'fine_tune_after_convergence': False,
    'fine_tune_learning_rate': None,
    'minimal_occurrence_limit': 5,
    'initialize_randomly': False,
    'datasets': ['icdar-2017', 'icdar-2019'],
}